input_root = "/mnt/62/Processed_Data/derivatives/qsirecon"
output_dir = "/media/storage/yalab-dev/derivatives/qsiparc"
# subjects = ["0350"]  # Optional: process specific subjects
# sessions = ["202012151539"]         # Optional: process specific sessions
force = false             # Set to true to overwrite existing outputs
log_level = "DEBUG"

[[atlases]]
name = "Schaefer2018N400n7Tian2020S3"
path = "/media/storage/yalab-dev/voxelops/Schaefer2018Tian2020_atlases/atlas-Schaefer2018N400n7Tian2020S3/atlas-Schaefer2018N400n7Tian2020S3_space-MNI152NLin2009cAsym_res-01_dseg.nii.gz"
lut = "/media/storage/yalab-dev/voxelops/Schaefer2018Tian2020_atlases/atlas-Schaefer2018N400n7Tian2020S3/atlas-Schaefer2018N400n7Tian2020S3_dseg.tsv"
space = "MNI152NLin2009cAsym"
resolution = "01"


# [[atlases]]
# name = "AAL"
# path = "/path/to/atlas/aal.nii.gz"
# space = "MNI152NLin2009cAsym"
